;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================

[colors]
background = #00000000
background-alt = #202020
foreground = #8ec07c
primary = #F0C674
secondary = #CC202020
alert = #A54242
disabled = #707880
disk = #ea6962
disk-underline = #CB433C
cpu = #e78a4e
cpu-underline = #D46B26
temp = #d8a657
temp-underline = #BC8631
memory = #458588
memory-underline = #286C6F
pulseaudio = #83a598
pulseaudio-underline = #5E8D7B
battery-normal = #689d6a
battery-normal-underline = #47844B

[bar/example]
width = 100%
height = 22pt
radius = 6

; dpi = 96

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 3pt

border-size = 4pt
border-color = #00000000

padding-left = 0
padding-right = 1

module-margin = 1

separator = |
separator-font = 2
separator-foreground = ${colors.disabled}

font-0 = JetBrainsMono Nerd Font Mono:style=Bold:size=9
font-1 = JetBrainsMono Nerd Font Mono:style=Bold:size=10.5;3

modules-left = xworkspaces xwindow
modules-center = date
#modules-right = filesystem pulseaudio xkeyboard memory cpu wlan eth date
modules-right = filesystem menu disk cpu temperature memory pulseaudio battery

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true


; wm-restack = generic
; wm-restack = bspwm
; wm-restack = i3

; override-redirect = true

; This module is not active by default (to enable it, add it to one of the
; modules-* list above).
; Please note that only a single tray can exist at any time. If you launch
; multiple bars with this module, only a single one will show it, the others
; will produce a warning. Which bar gets the module is timing dependent and can
; be quite random.
; For more information, see the documentation page for this module:
; https://polybar.readthedocs.io/en/stable/user/modules/tray.html
[module/systray]
type = internal/tray

format-margin = 8pt
tray-spacing = 16pt

[module/xworkspaces]
type = internal/xworkspaces

label-active = %name%
label-active-background = ${colors.background-alt}
label-active-underline= ${colors.primary}
label-active-padding = 1

label-occupied = %name%
label-occupied-padding = 1

label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

label-empty = %name%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1

[module/xwindow]
type = internal/xwindow
label = %title:0:60:...%
label-font = 2
label-foreground = ${colors.secondary}

[module/filesystem]
type = internal/fs
interval = 25

mount-0 = /

format-mounted = <label-mounted>
format-mounted-prefix = "DISK  "
format-mounted-prefix-foreground = ${colors.secondary}
format-mounted-prefix-background = ${colors.disk}
format-mounted-prefix-padding = 1
format-mounted-underline= ${colors.disk-underline}
label-mounted = %free%
label-mounted-background = ${colors.secondary}
label-mounted-foreground = ${colors.disk}
label-mounted-padding = 1

format-unmounted = <label-unmounted>
label-unmounted = %mountpoint% not mounted
label-unmounted-foreground = ${colors.disabled}

[module/pulseaudio]
type = internal/pulseaudio

format-volume-prefix = "VOL "
format-volume-prefix-foreground = ${colors.secondary}
format-volume-prefix-background = ${colors.pulseaudio}
format-volume-prefix-padding = 1
format-volume-underline = ${colors.pulseaudio-underline}

format-volume = <label-volume>

label-volume = %percentage%%
label-volume-foreground = ${colors.pulseaudio}
label-volume-background = ${colors.secondary}
label-volume-padding = 1

label-muted = VOL  muted
label-muted-foreground = ${colors.secondary}
label-muted-background = ${colors.pulseaudio}
label-muted-padding = 1
label-muted-underline = ${colors.pulseaudio-underline}

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock

label-layout = %layout%
label-layout-foreground = ${colors.primary}

label-indicator-padding = 2
label-indicator-margin = 1
label-indicator-foreground = ${colors.background}
label-indicator-background = ${colors.secondary}

[module/memory]
type = internal/memory
interval = 2
format-prefix = "RAM "
format-prefix-foreground = ${colors.secondary}
format-prefix-background = ${colors.memory}
format-underline= ${colors.memory-underline}
format-prefix-padding = 1

label = %gb_used%
label-foreground = ${colors.memory}
label-background = ${colors.secondary}
label-padding = 1

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = "CPU "
format-prefix-foreground = ${colors.secondary}
format-background = ${colors.cpu}
format-underline= ${colors.cpu-underline}
format-prefix-padding = 1
label = %percentage:2%%
label-foreground = ${colors.cpu}
label-background = ${colors.secondary}
label-padding = 1

[module/temperature]
type = internal/temperature

; Seconds to sleep between updates
; Default: 1
interval = 0.5

; Thermal zone to use
; To list all the zone types, run 
; $ for i in /sys/class/thermal/thermal_zone*; do echo "$i: $(<$i/type)"; done
; Default: 0
thermal-zone = 0

; Select thermal zone by name
; The name has to match the contents of /sys/class/thermal/thermal_zone*/type
; for the desired thermal zone.
; New in version 3.7.0
; Default: ""
zone-type = x86_pkg_temp

; Full path of temperature sysfs path
; Use `sensors` to find preferred temperature source, then run
; $ for i in /sys/class/hwmon/hwmon*/temp*_input; do echo "$(<$(dirname $i)/name): $(cat ${i%_*}_label 2>/dev/null || echo $(basename ${i%_*})) $(readlink -f $i)"; done
; to find path to desired file
; Default reverts to thermal zone setting
hwmon-path = /sys/devices/platform/coretemp.0/hwmon/hwmon2/temp1_input

; Base temperature for where to start the ramp (in degrees celsius)
; Default: 0
base-temperature = 20

; Threshold temperature to display warning label (in degrees celsius)
; Default: 80
warn-temperature = 60

format = <label>
format-prefix = "TEMP 󰴈 "
format-prefix-foreground = ${colors.secondary}
format-background = ${colors.temp}
format-underline= ${colors.temp-underline}
format-prefix-padding = 1
label = %temperature-c%
label-foreground = ${colors.temp}
label-background = ${colors.secondary}
label-padding = 1
[network-base]
type = internal/network
interval = 5
format-connected = <label-connected>
format-disconnected = <label-disconnected>
label-disconnected = %{F#F0C674}%ifname%%{F#707880} disconnected

[module/wlan]
inherit = network-base
interface-type = wireless
label-connected = %{F#F0C674}%ifname%%{F-} %essid% %local_ip%

[module/eth]
inherit = network-base
interface-type = wired
label-connected = %{F#F0C674}%ifname%%{F-} %local_ip%

[module/battery]
type = internal/battery

full-at = 99
low-at = 20

battery = BAT1
adapter = AC

format-charging = <animation-charging> <label-charging>
format-charging-background = ${colors.battery-normal}

format-discharging = <ramp-capacity> <label-discharging>
format-discharging-background = ${colors.battery-normal}

format-full = <ramp-capacity> <label-full>
format-full-background = ${colors.battery-normal}

format-low = <label-low> <animation-low>
format-low-background = #cc241d

format-charging-underline= ${colors.battery-normal-underline}
format-discharging-underline= ${colors.battery-normal-underline}
format-full-underline= ${colors.battery-normal-underline}
format-low-underline= ${colors.battery-normal-underline}
; Available tokens:
;   %percentage% (default) - is set to 100 if full-at is reached
;   %percentage_raw%
;   %time%
;   %consumption% (shows current charge rate in watts)
label-charging = Charging %percentage%%
label-charging-foreground = ${colors.battery-normal}
label-charging-background = ${colors.secondary}
label-charging-padding = 1

; Available tokens:
;   %percentage% (default) - is set to 100 if full-at is reached
;   %percentage_raw%
;   %time%
;   %consumption% (shows current discharge rate in watts)
label-discharging = Discharging %percentage%%
label-discharging-foreground = ${colors.battery-normal}
label-discharging-background = ${colors.secondary}
label-discharging-padding = 1

; Available tokens:
;   %percentage% (default) - is set to 100 if full-at is reached
;   %percentage_raw%
label-full = Fully charged
label-full-foreground = ${colors.battery-normal}
label-full-background = ${colors.secondary}
label-full-padding = 1

; Available tokens:
;   %percentage% (default) - is set to 100 if full-at is reached
;   %percentage_raw%
;   %time%
;   %consumption% (shows current discharge rate in watts)
; New in version 3.6.0
label-low = BATTERY LOW
label-low-foreground = #cc241d
label-low-background = ${colors.secondary}
label-low-padding = 1

; Only applies if <ramp-capacity> is used
ramp-capacity-foreground = ${colors.secondary}
ramp-capacity-padding = 1
ramp-capacity-0 = BAT 󰂎
ramp-capacity-1 = BAT 󰁺
ramp-capacity-2 = BAT 󰁻
ramp-capacity-3 = BAT 󰁽
ramp-capacity-4 = BAT 󰁿
ramp-capacity-5 = BAT 󰁾
ramp-capacity-6 = BAT 󰂀
ramp-capacity-7 = BAT 󰂁
ramp-capacity-8 = BAT 󰂂
ramp-capacity-9 = BAT 󰁹

; Only applies if <bar-capacity> is used
bar-capacity-width = 10

; Only applies if <animation-charging> is used
animation-charging-foreground = ${colors.secondary}
animation-charging-padding = 1
animation-charging-0 = BAT 󰢜
animation-charging-1 = BAT 󰢝
animation-charging-2 = BAT 󰂅
;animation-charging-3 = 󰁽
;animation-charging-4 = 󰁿
;animation-charging-5 = 󰁾
;animation-charging-6 = 󰂀
;animation-charging-7 = 󰂁
;animation-charging-8 = 󰂂
;animation-charging-9 = 󰁹
; Framerate in milliseconds
animation-charging-framerate = 750

; Only applies if <animation-discharging> is used
animation-discharging-0 = BAT 󰁹
animation-discharging-1 = BAT 󰂂
animation-discharging-2 = BAT 󰂁
animation-discharging-3 = BAT 󰂀
animation-discharging-4 = BAT 󰁾
animation-discharging-5 = BAT 󰁿
animation-discharging-6 = BAT 󰁽
animation-discharging-7 = BAT 󰁻
animation-discharging-8 = BAT 󰁺
animation-discharging-9 = BAT 󰂎
; Framerate in milliseconds
animation-discharging-framerate = 500

; Only applies if <animation-low> is used
; New in version 3.6.0
animation-low-0 = !
animation-low-1 = 
animation-low-framerate = 200

format-underline= ${colors.primary}
format-background = ${colors.secondary}
format-padding = 1
[module/date]
type = internal/date
interval = 1

date = %H:%M
date-alt = %a-%d-%b %H:%M:%S

label = %date%
label-foreground = ${colors.foreground}
label-background = ${colors.secondary}
label-padding = 1
format = DATE  <label>
format-font = 2
format-alignment = center
format-foreground = ${colors.secondary}
format-background = #689d6a
format-padding = 1

[settings]
screenchange-reload = true
pseudo-transparency = true

; vim:ft=dosini
